### ISSUE TITLE
“Glyconote - MS2 - Identification . exe ” missing

### ISSUE THREAD

**Issue by holandir** [MingqiLiu/GlycoNote#1]
Hello,

I see that the file “Glyconote-MS2-Identification.exe” is missing.
In the publication it is described, that this file should be included here.
Is it possible that you upload this file?

**Comment by MingqiLiu** [comment]
Git has 25MB file size limit.
“Glyconote-MS2-Identification.exe”, which use Pyinstaller to package the same python file in the repository, has the file size of 300MB (I don't know how Pyinstaller works).
Can you download “Glyconote-MS2-Identification.exe” from the Supplementary data link in the paper?
All data and program was uploaded to Massive repository, which has no file size limit.
Thank you.

**Comment by holandir** [comment]
Thank you, I found the program!
